version: '3.8'
services:
  data-source:
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      start_period: 5s
      interval: 5s
      timeout: 20s
      retries: 4
  app:
    depends_on:
      data-source:
        condition: service_healthy
    image: node:19
    volumes:
      - ./dist:/opt/app
      - ./node_modules:/opt/app/node_modules
    env_file:
      - ./.env
    working_dir: /opt/app
    command: node app.js
    ports:
      - 9000:9000
    networks:
      - backend
networks:
  backend:
